[project]
name = "xiaohongshu-data-visualization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.2",
    "plotly>=6.7.0",
    "polars>=1.40.1",
    "pygwalker>=0.5.0.1",
    "streamlit>=1.57.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
